import type { InsertCategory, InsertVisualOptions, InsertAudioSettings, AudioSourceType, SceneFilterType, SceneMotionType } from "../types";

export interface CatalogItem {
  type: string;
  category: InsertCategory;
  name: string;
  icon: string;
  description: string;
  defaultDuration: number;
  defaultPosition: "top" | "bottom" | "center" | "left" | "right" | "top-left" | "top-right" | "bottom-left" | "bottom-right";
  defaultSize: number;
  defaultAudioSource?: AudioSourceType;
  subCategory?: string;
  defaultVisualOptions?: InsertVisualOptions;
  defaultAudioSettings?: InsertAudioSettings;
  defaultContent?: {
    primaryText?: string;
    secondaryText?: string;
    book?: string;
    chapter?: string;
    verse?: string;
    author?: string;
    number?: string;
    label?: string;
    items?: string[];
  };
}

// ---------------- 5 MAIN STUDIO CATEGORIES IN EXACT REQUIRED ORDER ----------------
// 1. Logo, 2. Call to Action, 3. Stickers, 4. Text Content, 5. Audio Visualisers
export interface StudioCategoryDef {
  id: InsertCategory;
  name: string;
  icon: string;
  description: string;
  subcategories?: { id: string; name: string; icon: string }[];
}

export const STUDIO_CATEGORIES: StudioCategoryDef[] = [
  {
    id: "logo",
    name: "Logo",
    icon: "🏷️",
    description: "Upload and place your official brand logo watermark on the video",
  },
  {
    id: "call_to_action",
    name: "Call to Action",
    icon: "📣",
    description: "Subscribe buttons, follow badges, like & share callouts, and shop banners",
    subcategories: [
      { id: "all", name: "All CTAs", icon: "📣" },
      { id: "social", name: "Social & Subscribe", icon: "🔔" },
      { id: "action", name: "Shop & Links", icon: "🛍️" },
    ],
  },
  {
    id: "stickers",
    name: "Stickers",
    icon: "✨",
    description: "3D animated stickers, badges, trophies, emojis, and visual reactions with sound FX",
    subcategories: [
      { id: "all", name: "All Stickers", icon: "✨" },
      { id: "reactions", name: "Reactions & Badges", icon: "⭐" },
      { id: "objects", name: "3D Elements", icon: "🚀" },
    ],
  },
  {
    id: "content_cards",
    name: "Text Content",
    icon: "📜",
    description: "Lower thirds, title cards, quotes, scriptures, and educational information frames",
    subcategories: [
      { id: "all", name: "All Text Content", icon: "📜" },
      { id: "lower_third", name: "Lower Thirds & Titles", icon: "👤" },
      { id: "quotes_scripture", name: "Quotes & Scripture", icon: "💬" },
      { id: "info_cards", name: "Facts & Lessons", icon: "💡" },
    ],
  },
  {
    id: "audio_visualizers",
    name: "Audio Visualisers",
    icon: "📊",
    description: "Waveforms, frequency bars, speech-reactive meters, and relaxation zen pulses",
    subcategories: [
      { id: "all", name: "All Visualisers", icon: "📊" },
      { id: "waves", name: "Audio Waves & Bars", icon: "〰️" },
      { id: "speech", name: "Speech Reactive", icon: "🎙️" },
      { id: "zen", name: "Relaxation / Zen", icon: "🧘" },
    ],
  },
];

// ---------------- COMPLETE CATALOG ITEMS ----------------
export const CATALOG_ITEMS: Record<string, CatalogItem[]> = {
  logo: [
    {
      type: "customer_logo",
      category: "logo",
      name: "Brand Logo Watermark",
      icon: "🏷️",
      description: "Display your official transparent PNG brand logo with adjustable scale and opacity",
      defaultDuration: 15,
      defaultPosition: "top-right",
      defaultSize: 1.0,
      defaultVisualOptions: { has3DLook: false },
    },
  ],

  call_to_action: [
    {
      type: "subscribe_cta",
      category: "call_to_action",
      subCategory: "social",
      name: "3D Subscribe & Bell Button",
      icon: "🔔",
      description: "Eye-catching 3D red subscribe pill with glowing notification bell",
      defaultDuration: 4.5,
      defaultPosition: "bottom",
      defaultSize: 1.1,
      defaultContent: { primaryText: "SUBSCRIBE" },
      defaultVisualOptions: { has3DLook: true, animationPreset: "bounce" },
      defaultAudioSettings: { soundUrl: "/sounds/ting.ogg", soundName: "Ting Bell", volume: 0.8 },
    },
    {
      type: "follow_cta",
      category: "call_to_action",
      subCategory: "social",
      name: "Follow on Social Badge",
      icon: "✨",
      description: "Curved 3D azure social pill inviting viewers to follow your channel",
      defaultDuration: 4.0,
      defaultPosition: "bottom-left",
      defaultSize: 1.0,
      defaultContent: { primaryText: "FOLLOW FOR MORE" },
      defaultVisualOptions: { has3DLook: true, animationPreset: "pop_in" },
    },
    {
      type: "like_share_cta",
      category: "call_to_action",
      subCategory: "social",
      name: "Like & Share Callout",
      icon: "👍",
      description: "Interactive thumbs-up and share reminder banner",
      defaultDuration: 4.0,
      defaultPosition: "bottom-right",
      defaultSize: 1.0,
      defaultContent: { primaryText: "LIKE & SHARE" },
      defaultVisualOptions: { has3DLook: true, animationPreset: "bounce" },
      defaultAudioSettings: { soundUrl: "/sounds/jump_pop.wav", soundName: "Jump Pop", volume: 0.75 },
    },
    {
      type: "buy_now_cta",
      category: "call_to_action",
      subCategory: "action",
      name: "Shop & Buy Now Pill",
      icon: "🛍️",
      description: "Vibrant emerald e-commerce callout urging viewers to shop now",
      defaultDuration: 5.0,
      defaultPosition: "bottom",
      defaultSize: 1.0,
      defaultContent: { primaryText: "SHOP NOW — 20% OFF" },
      defaultVisualOptions: { has3DLook: true, animationPreset: "pop_in" },
      defaultAudioSettings: { soundUrl: "/sounds/ting.ogg", soundName: "Ting Bell", volume: 0.8 },
    },
    {
      type: "visit_website_cta",
      category: "call_to_action",
      subCategory: "action",
      name: "Visit Website / Link",
      icon: "🔗",
      description: "Clean modern link card for bio, resources, or web landing page",
      defaultDuration: 5.0,
      defaultPosition: "bottom",
      defaultSize: 1.0,
      defaultContent: { primaryText: "LINK IN DESCRIPTION" },
      defaultVisualOptions: { has3DLook: true, animationPreset: "pop_in" },
    },
    {
      type: "cta",
      category: "call_to_action",
      subCategory: "action",
      name: "Full Call-to-Action Card",
      icon: "🚀",
      description: "Direct invitation frame encouraging viewers to take action",
      defaultDuration: 5.0,
      defaultPosition: "bottom",
      defaultSize: 1.0,
      defaultContent: { label: "GET STARTED", primaryText: "Visit our site for the full checklist" },
    },
  ],

  stickers: [
    {
      type: "emoji_star",
      category: "stickers",
      subCategory: "reactions",
      name: "3D Golden Star",
      icon: "⭐",
      description: "Extruded 3D star with metallic sheen, bevel facets, and warm specular shine",
      defaultDuration: 3.5,
      defaultPosition: "top-left",
      defaultSize: 1.0,
      defaultVisualOptions: { has3DLook: true, assetUrl: "/stickers/star_3d.svg", animationPreset: "pop_in" },
      defaultAudioSettings: { soundUrl: "/sounds/ting.ogg", soundName: "Ting Bell Chime", volume: 0.8 },
    },
    {
      type: "heart",
      category: "stickers",
      subCategory: "reactions",
      name: "3D Ruby Heart",
      icon: "❤️",
      description: "Glossy 3D ruby heart with curved surface reflections and soft ambient occlusion",
      defaultDuration: 3.5,
      defaultPosition: "center",
      defaultSize: 1.0,
      defaultVisualOptions: { has3DLook: true, assetUrl: "/stickers/heart_3d.svg", animationPreset: "pulse" },
      defaultAudioSettings: { soundUrl: "/sounds/jump_pop.wav", soundName: "Jump Pop", volume: 0.75 },
    },
    {
      type: "emoji_fire",
      category: "stickers",
      subCategory: "reactions",
      name: "3D Volumetric Fire",
      icon: "🔥",
      description: "Layered 3D hot flame with glowing core, amber corona, and depth shadow",
      defaultDuration: 3.5,
      defaultPosition: "top-right",
      defaultSize: 1.0,
      defaultVisualOptions: { has3DLook: true, assetUrl: "/stickers/fire_3d.svg", animationPreset: "float_3d" },
      defaultAudioSettings: { soundUrl: "/sounds/whoosh_appear.wav", soundName: "Whoosh Appear", volume: 0.8 },
    },
    {
      type: "bell",
      category: "stickers",
      subCategory: "objects",
      name: "3D Golden Bell",
      icon: "🔔",
      description: "Lustrous brass 3D bell with curved specular glint and ringing clapper",
      defaultDuration: 3.5,
      defaultPosition: "top-right",
      defaultSize: 1.0,
      defaultVisualOptions: { has3DLook: true, assetUrl: "/stickers/bell_3d.svg", animationPreset: "bounce" },
      defaultAudioSettings: { soundUrl: "/sounds/bicycle_bell.ogg", soundName: "Ding-Dong Bell", volume: 0.85 },
    },
    {
      type: "check",
      category: "stickers",
      subCategory: "reactions",
      name: "3D Verified Badge",
      icon: "✅",
      description: "3D starburst badge in vibrant cyber cyan-blue with white checkmark",
      defaultDuration: 3.5,
      defaultPosition: "top-right",
      defaultSize: 1.0,
      defaultVisualOptions: { has3DLook: true, assetUrl: "/stickers/verified_3d.svg", animationPreset: "pop_in" },
      defaultAudioSettings: { soundUrl: "/sounds/achievement_bell.wav", soundName: "Achievement Bell", volume: 0.8 },
    },
    {
      type: "trophy",
      category: "stickers",
      subCategory: "objects",
      name: "3D Winner Trophy",
      icon: "🏆",
      description: "3D gold winner cup on slate pedestal with medallion star",
      defaultDuration: 4.0,
      defaultPosition: "center",
      defaultSize: 1.1,
      defaultVisualOptions: { has3DLook: true, assetUrl: "/stickers/trophy_3d.svg", animationPreset: "bounce" },
      defaultAudioSettings: { soundUrl: "/sounds/applause.ogg", soundName: "Audience Applause", volume: 0.85 },
    },
    {
      type: "sparkle",
      category: "stickers",
      subCategory: "reactions",
      name: "3D Diamond Sparkle",
      icon: "💎",
      description: "Multi-axis prismatic 3D sparkle flare with deep blue-to-white light core",
      defaultDuration: 3.5,
      defaultPosition: "top-left",
      defaultSize: 1.0,
      defaultVisualOptions: { has3DLook: true, assetUrl: "/stickers/sparkle_3d.svg", animationPreset: "spin" },
      defaultAudioSettings: { soundUrl: "/sounds/ting.ogg", soundName: "Ting Bell", volume: 0.75 },
    },
    {
      type: "trending",
      category: "stickers",
      subCategory: "objects",
      name: "3D Trending Rocket",
      icon: "🚀",
      description: "Dynamic 3D rocket ship with fiery exhaust booster and metallic fuselage",
      defaultDuration: 4.0,
      defaultPosition: "bottom-left",
      defaultSize: 1.1,
      defaultVisualOptions: { has3DLook: true, assetUrl: "/stickers/trending_3d.svg", animationPreset: "float_3d" },
      defaultAudioSettings: { soundUrl: "/sounds/whoosh_appear.wav", soundName: "Whoosh Appear", volume: 0.85 },
    },
    {
      type: "camera",
      category: "stickers",
      subCategory: "objects",
      name: "3D Studio Camera",
      icon: "📷",
      description: "3D dark slate camera body with coated optical cyan glass lens",
      defaultDuration: 3.5,
      defaultPosition: "center",
      defaultSize: 1.0,
      defaultVisualOptions: { has3DLook: true, assetUrl: "/stickers/camera_3d.svg", animationPreset: "pop_in" },
      defaultAudioSettings: { soundUrl: "/sounds/camera_shutter.ogg", soundName: "Camera Shutter", volume: 0.9 },
    },
    {
      type: "like",
      category: "stickers",
      subCategory: "reactions",
      name: "3D Golden Thumbs Up",
      icon: "👍",
      description: "Tactile curved 3D gold thumbs up gesture with blue cuff",
      defaultDuration: 4.0,
      defaultPosition: "bottom-right",
      defaultSize: 1.0,
      defaultVisualOptions: { has3DLook: true, assetUrl: "/stickers/thumbsup_3d.svg", animationPreset: "bounce" },
      defaultAudioSettings: { soundUrl: "/sounds/jump_pop.wav", soundName: "Jump Pop", volume: 0.8 },
    },
    {
      type: "play",
      category: "stickers",
      subCategory: "objects",
      name: "3D Crimson Play Button",
      icon: "▶️",
      description: "Translucent frosted 3D crimson glass button with glowing arrow",
      defaultDuration: 4.0,
      defaultPosition: "center",
      defaultSize: 1.0,
      defaultVisualOptions: { has3DLook: true, assetUrl: "/stickers/play_3d.svg", animationPreset: "pulse" },
      defaultAudioSettings: { soundUrl: "/sounds/ui_beep.ogg", soundName: "UI Beep", volume: 0.7 },
    },
    {
      type: "money",
      category: "stickers",
      subCategory: "objects",
      name: "3D Gold Coins Stack",
      icon: "💰",
      description: "Layered 3D gold coin stack with ribbed edges and dollar embossing",
      defaultDuration: 3.5,
      defaultPosition: "bottom-right",
      defaultSize: 1.0,
      defaultVisualOptions: { has3DLook: true, assetUrl: "/stickers/money_3d.svg", animationPreset: "bounce" },
      defaultAudioSettings: { soundUrl: "/sounds/ting.ogg", soundName: "Ting Bell", volume: 0.8 },
    },
  ],

  content_cards: [
    // Subcategory: lower_third
    {
      type: "person",
      category: "content_cards",
      subCategory: "lower_third",
      name: "Speaker Lower-Third",
      icon: "👤",
      description: "Clean presenter name and job title badge in lower corner",
      defaultDuration: 4.0,
      defaultPosition: "bottom-left",
      defaultSize: 1.0,
      defaultContent: { primaryText: "Dr. Elizabeth Vance", secondaryText: "Lead Astrobiologist, NASA" },
    },
    {
      type: "chapter",
      category: "content_cards",
      subCategory: "lower_third",
      name: "Chapter / Section Title Card",
      icon: "🔖",
      description: "Cinematic full-width title divider for introducing a new section",
      defaultDuration: 4.0,
      defaultPosition: "center",
      defaultSize: 1.0,
      defaultContent: { label: "CHAPTER 2", primaryText: "The Turning Point" },
    },
    {
      type: "location",
      category: "content_cards",
      subCategory: "lower_third",
      name: "Location Card",
      icon: "📍",
      description: "Geographical locator tag for city, country or place",
      defaultDuration: 3.5,
      defaultPosition: "bottom-left",
      defaultSize: 0.9,
      defaultContent: { label: "LOCATION", primaryText: "Kyoto, Japan" },
    },
    // Subcategory: quotes_scripture
    {
      type: "quote",
      category: "content_cards",
      subCategory: "quotes_scripture",
      name: "Quote Frame",
      icon: "💬",
      description: "Elegant typography frame for famous sayings or citations",
      defaultDuration: 5.0,
      defaultPosition: "center",
      defaultSize: 1.0,
      defaultContent: {
        primaryText: "The only limit to our realization of tomorrow is our doubts of today.",
        author: "Franklin D. Roosevelt",
      },
    },
    {
      type: "scripture",
      category: "content_cards",
      subCategory: "quotes_scripture",
      name: "Holy Scripture Frame",
      icon: "📖",
      description: "Dedicated spiritual scripture with book, chapter & verse in golden trim",
      defaultDuration: 6.0,
      defaultPosition: "center",
      defaultSize: 1.0,
      defaultContent: {
        primaryText: "For God so loved the world, that he gave his only begotten Son.",
        book: "John",
        chapter: "3",
        verse: "16",
      },
    },
    // Subcategory: info_cards
    {
      type: "key_point",
      category: "content_cards",
      subCategory: "info_cards",
      name: "Key Takeaway Frame",
      icon: "💡",
      description: "Highlights the central point or moral from narration",
      defaultDuration: 4.5,
      defaultPosition: "bottom",
      defaultSize: 1.0,
      defaultContent: {
        label: "KEY TAKEAWAY",
        primaryText: "Consistency compounds faster than occasional intensity.",
      },
    },
    {
      type: "fact",
      category: "content_cards",
      subCategory: "info_cards",
      name: "Did You Know? Fact Card",
      icon: "🧠",
      description: "Fascinating educational fact callout frame",
      defaultDuration: 5.0,
      defaultPosition: "top",
      defaultSize: 1.0,
      defaultContent: {
        label: "DID YOU KNOW?",
        primaryText: "Honey found in ancient Egyptian tombs is still perfectly edible after 3,000 years.",
      },
    },
    {
      type: "definition",
      category: "content_cards",
      subCategory: "info_cards",
      name: "Definition Frame",
      icon: "📚",
      description: "Explains an uncommon word, term or technical concept",
      defaultDuration: 5.0,
      defaultPosition: "center",
      defaultSize: 1.0,
      defaultContent: {
        label: "DEFINITION",
        primaryText: "Serendipity",
        secondaryText: "The occurrence of events by chance in a happy or beneficial way.",
      },
    },
    {
      type: "training",
      category: "content_cards",
      subCategory: "info_cards",
      name: "Training / Lesson Step",
      icon: "🎓",
      description: "Structured step-by-step instruction or lesson card",
      defaultDuration: 5.5,
      defaultPosition: "center",
      defaultSize: 1.0,
      defaultContent: {
        label: "STEP 1 OF 3",
        primaryText: "Calibrate your baseline and inspect all inputs thoroughly.",
      },
    },
    {
      type: "stats",
      category: "content_cards",
      subCategory: "info_cards",
      name: "Statistics Highlight",
      icon: "📈",
      description: "Large dynamic metric counter highlighting data",
      defaultDuration: 4.5,
      defaultPosition: "center",
      defaultSize: 1.0,
      defaultContent: { number: "84%", primaryText: "of users report higher satisfaction within 14 days" },
    },
  ],

  audio_visualizers: [
    // Subcategory: waves
    {
      type: "waveform",
      category: "audio_visualizers",
      subCategory: "waves",
      name: "Dynamic Acoustic Waveform",
      icon: "〰️",
      description: "Smooth continuous acoustic wave placed still on screen, reacts to voice or music",
      defaultDuration: 8.0,
      defaultPosition: "bottom",
      defaultSize: 1.0,
      defaultAudioSource: "voice",
    },
    {
      type: "mirror_wave",
      category: "audio_visualizers",
      subCategory: "waves",
      name: "Mirror Waveform",
      icon: "🪞",
      description: "Symmetrical dual wave oscillating from center, static position",
      defaultDuration: 8.0,
      defaultPosition: "bottom",
      defaultSize: 1.0,
      defaultAudioSource: "voice",
    },
    {
      type: "equalizer_bars",
      category: "audio_visualizers",
      subCategory: "waves",
      name: "Studio Equalizer Bars",
      icon: "📶",
      description: "Multi-frequency studio level bars reacting dynamically to audio",
      defaultDuration: 8.0,
      defaultPosition: "bottom",
      defaultSize: 1.0,
      defaultAudioSource: "voice",
    },
    {
      type: "circular_wave",
      category: "audio_visualizers",
      subCategory: "waves",
      name: "Circular Frequency Wave",
      icon: "⭕",
      description: "Orbital pulsating circular sound wave anchored in place",
      defaultDuration: 8.0,
      defaultPosition: "center",
      defaultSize: 1.0,
      defaultAudioSource: "voice",
    },
    {
      type: "spectrum",
      category: "audio_visualizers",
      subCategory: "waves",
      name: "Spectrum Visualizer",
      icon: "🌈",
      description: "Full spectrum colored sound analyzer bars",
      defaultDuration: 8.0,
      defaultPosition: "bottom",
      defaultSize: 1.0,
      defaultAudioSource: "voice",
    },
    // Subcategory: speech
    {
      type: "speech_spectrum",
      category: "audio_visualizers",
      subCategory: "speech",
      name: "Speech Formant Spectrum",
      icon: "🎙️",
      description: "Vocal formant frequency bars connected directly to voiceover speech",
      defaultDuration: 8.0,
      defaultPosition: "bottom",
      defaultSize: 0.9,
      defaultAudioSource: "voice",
    },
    {
      type: "voice_pulse",
      category: "audio_visualizers",
      subCategory: "speech",
      name: "Voice Dialogue Pulse",
      icon: "🔊",
      description: "Concentric ring pulse reacting strictly to speech syllables",
      defaultDuration: 6.0,
      defaultPosition: "center",
      defaultSize: 1.0,
      defaultAudioSource: "voice",
    },
    {
      type: "energy_ring",
      category: "audio_visualizers",
      subCategory: "speech",
      name: "Energy Speech Ring",
      icon: "💍",
      description: "Luminous glowing ring that expands during speech vocalization",
      defaultDuration: 6.0,
      defaultPosition: "center",
      defaultSize: 1.0,
      defaultAudioSource: "voice",
    },
    {
      type: "minimal_voice",
      category: "audio_visualizers",
      subCategory: "speech",
      name: "Minimal Talking Dots",
      icon: "🗣️",
      description: "Three modern talking dots that dance when vocalizing, still in idle",
      defaultDuration: 6.0,
      defaultPosition: "bottom-right",
      defaultSize: 0.8,
      defaultAudioSource: "voice",
    },
    // Subcategory: zen
    {
      type: "breathing_circle",
      category: "audio_visualizers",
      subCategory: "zen",
      name: "Meditation Breathing Circle",
      icon: "🧘",
      description: "Calm 4-second inhale / 4-second exhale guided pacing circle",
      defaultDuration: 10.0,
      defaultPosition: "center",
      defaultSize: 1.0,
      defaultAudioSource: "music",
    },
    {
      type: "gentle_wave",
      category: "audio_visualizers",
      subCategory: "zen",
      name: "Gentle Zen Wave",
      icon: "🌊",
      description: "Slow undulating peaceful gradient waves",
      defaultDuration: 10.0,
      defaultPosition: "bottom",
      defaultSize: 1.0,
      defaultAudioSource: "music",
    },
    {
      type: "water_ripple",
      category: "audio_visualizers",
      subCategory: "zen",
      name: "Water Ripple Reflection",
      icon: "💧",
      description: "Serene concentric ripples on calm water surface",
      defaultDuration: 8.0,
      defaultPosition: "center",
      defaultSize: 1.0,
      defaultAudioSource: "music",
    },
  ],
};

// Aliases for backwards compatibility with any existing items
CATALOG_ITEMS.speech_reactive = CATALOG_ITEMS.audio_visualizers;
CATALOG_ITEMS.meditation = CATALOG_ITEMS.audio_visualizers;
CATALOG_ITEMS.other_cards = CATALOG_ITEMS.content_cards;
CATALOG_ITEMS.branding = CATALOG_ITEMS.logo;

export const SCENE_FILTERS: { id: SceneFilterType; name: string; desc: string }[] = [
  { id: "none", name: "Natural (Original)", desc: "Unprocessed original colors" },
  { id: "cinematic", name: "Cinematic Film", desc: "Balanced teal & orange film look" },
  { id: "warm_movie", name: "Warm Movie", desc: "Golden honey tones with soft shadows" },
  { id: "golden_hour", name: "Golden Hour", desc: "Rich warm sunset glow" },
  { id: "black_and_white", name: "Monochrome Noir", desc: "Classic high contrast black and white" },
  { id: "vintage", name: "Vintage 1970s", desc: "Warm nostalgic sepia wash" },
  { id: "soft_glow", name: "Dreamy Bloom", desc: "Ethereal luminous highlights" },
  { id: "cold_blue", name: "Nordic Blue", desc: "Cool desaturated atmospheric palette" },
];

export const SCENE_MOTIONS: { id: SceneMotionType; name: string; desc: string }[] = [
  { id: "none", name: "Static (No Motion)", desc: "Fixed still frame without movement" },
  { id: "slow_zoom", name: "Slow Zoom In", desc: "Gentle cinematic push towards subject" },
  { id: "pan_left", name: "Pan Left", desc: "Smooth horizontal glide across the frame" },
  { id: "pan_right", name: "Pan Right", desc: "Smooth horizontal sweep to the right" },
  { id: "ken_burns", name: "Ken Burns Classic", desc: "Subtle diagonal pan & zoom documentary motion" },
];
