export interface FaqEntry { id: string; category: string; question: string; answer: string; keywords: string }
interface Concept { category: string; term: string; meaning: string; purpose: string; control: string; caution: string; export: string }
const c = (category: string, term: string, meaning: string, purpose: string, control: string, caution: string, output: string): Concept => ({ category, term, meaning, purpose, control, caution, export: output });

/**
 * One hundred and ten real concepts from the Scenering workflow. Every concept
 * covers meaning, control, common errors and final-output impact; the first
 * sixty also answer the separate “why use it?” uncertainty. This produces
 * exactly 500 useful, searchable answers without dropping specialist terms.
 */
const CONCEPTS: Concept[] = [
  c("Getting started", "Scenering", "Scenering is a web application that turns a script or prepared audio into an editable, scene-based faceless video.", "It brings visual research, narration, captions, finishing and export into one guided workflow.", "Begin with Get Started Free, verify your email, then create a project in Setup.", "Do not expect a one-click black box; review each stage so the finished video reflects your intent.", "Scenering produces a video file using the format and quality selected in Project Setup."),
  c("Getting started", "the six-step workflow", "The studio moves through Setup, Scenes, Voiceover, Captions, Video Studio and Render.", "The order prevents later styling decisions from hiding problems in the script or scene structure.", "Use the numbered phase bar at the top; completed work remains editable when you move backward.", "Do not treat moving forward as permanent—return to an earlier step whenever something needs correction.", "All six stages contribute to the final file, but previews between them do not count as final exports."),
  c("Getting started", "a faceless video", "A faceless video communicates with visuals, narration, captions and graphics without requiring the creator to appear on camera.", "It suits education, information, storytelling, training and channels where filming is impractical.", "Use relevant scene imagery, a suitable narrator and readable captions to carry the story.", "Faceless does not mean impersonal; generic visuals and monotone narration can still weaken the result.", "The final export contains the assembled media, not a recording of you using the editor."),
  c("Getting started", "browser-based editing", "Browser-based editing means Scenering runs in a modern web browser rather than requiring desktop installation.", "It makes the studio accessible across common computers while using browser media capabilities.", "Use a current Chromium-based browser for the broadest rendering support and keep the tab open during export.", "Private browsing, aggressive storage clearing and unsupported browsers can remove local project media or limit rendering.", "Rendering capability and speed depend partly on the browser and device."),
  c("Getting started", "the Setup screen", "Setup is the project control room for title, source content, format, pacing, motion and render profile.", "Decisions made here establish the canvas and initial scene structure before detailed editing.", "Review destination, aspect ratio, resolution and narration choices before creating scenes.", "Changing format late is possible, but may require reframing images, captions and overlays.", "Setup choices determine the dimensions, frame rate and encoding plan used by final export."),

  c("Accounts and security", "registration", "Registration creates a Scenering account with email, display name and a securely hashed password.", "An account provides membership, session, usage and billing identity without merging those concepts together.", "Choose Get Started Free, complete the form and follow the verification link.", "Do not reuse a weak password or enter an email you cannot access.", "Registration itself does not consume usage or create a paid subscription."),
  c("Accounts and security", "email verification", "Email verification confirms that you control the address used for your account.", "It protects account recovery and prevents another person from registering your address without access to it.", "Open the expiring verification link sent after registration; request a new one if it expires.", "Do not share verification links because they function as temporary account tokens.", "Verification changes account access, not video content or export quality."),
  c("Accounts and security", "a session", "A session is the secure, temporary sign-in state stored in an HttpOnly browser cookie.", "It keeps you signed in without exposing the session token to normal page scripts.", "Sign in on the Login page and use Sign out from the corner menu when finished on a shared device.", "Do not assume closing one tab signs out every open tab on the same browser.", "Sessions control access to account APIs but do not alter a rendered video."),
  c("Accounts and security", "password reset", "Password reset uses a single-use, expiring link to let you choose a new password.", "It restores access without emailing or storing your existing password.", "Choose Forgot password, enter your email and use the link within one hour.", "Scenering will not reveal whether an address exists, and legitimate support should never ask for your password.", "Resetting a password leaves membership, projects and export history intact."),
  c("Accounts and security", "transactional email", "Transactional email includes verification, resets, billing, security and essential account notices.", "These messages are necessary to operate and protect the account.", "Keep the account email current and check spam folders when expecting a security message.", "Do not confuse required account messages with optional marketing email.", "Email preferences do not change video rendering."),

  c("Plans and billing", "Free membership", "Free is a real membership that can create, preview, correct and export finished basic videos.", "It lets new users understand the complete workflow without payment details.", "Register and verify an account; Free is assigned automatically.", "Free has weekly final-export allowances and a smaller creative library, but previews remain available.", "Free exports use the same core renderer while available voices, styles and capacity follow the plan."),
  c("Plans and billing", "SceneFlow", "SceneFlow is the regular-production plan with the full creative toolkit and a configurable 20-minute weekly export allowance.", "It is intended for creators who need more voices, captions, studio tools and production capacity.", "Choose monthly or yearly billing from Pricing or Account and complete configured Lemon Squeezy checkout.", "Returning from checkout alone does not grant access; verified subscription status must arrive by webhook.", "SceneFlow unlocks available premium creative controls and increases final-export capacity."),
  c("Plans and billing", "SceneForge", "SceneForge is the high-capacity plan with a configurable 60-minute weekly export allowance.", "It supports busier publishing schedules and future high-volume workflow features.", "Upgrade through Account or Pricing using the configured monthly or yearly option.", "Do not choose it solely for a feature marked Future Feature; only implemented tools are active.", "Its exports use the selected render profile while capacity and processing entitlement are higher."),
  c("Plans and billing", "monthly versus yearly billing", "Monthly and yearly are billing intervals for SceneFlow and SceneForge, not separate plans.", "Yearly billing lowers the effective monthly cost while charging the annual amount at once.", "Use the interval switch to compare exact totals and displayed annual savings.", "Do not read the annual monthly equivalent as a monthly charge; the full annual amount is billed yearly.", "Billing interval does not change video quality or tools within the same plan."),
  c("Plans and billing", "verified webhook billing", "A billing webhook is a signed server-to-server message from Lemon Squeezy about subscription state.", "It prevents a visitor from gaining paid access merely by opening a success URL.", "Administrators configure variant IDs and a webhook secret; customers complete normal checkout.", "Never expose webhook secrets or API keys in frontend code.", "Only verified active status updates paid entitlements; video files themselves contain no billing data."),

  c("Projects and setup", "a project", "A project is the saved collection of script, scenes, visuals, narration, captions, studio inserts and render settings.", "It keeps every decision for one video together and editable.", "Create or select projects from Setup and give each a descriptive title.", "Do not use one project for unrelated videos, because scene media and settings can become confusing.", "A project can produce multiple previews and final exports in different supported formats."),
  c("Projects and setup", "project preservation", "Project preservation means changing or ending a paid plan does not automatically delete projects.", "It lets an account return to Free without losing creative work.", "Keep projects in the studio and manage subscription separately in Account.", "Local browser media can still be lost if browser storage is cleared, so keep original uploads elsewhere.", "Preserved projects may contain premium choices that require entitlement before reuse or export."),
  c("Projects and setup", "single-scene mode", "Single-scene mode keeps the entire source as one continuous scene rather than splitting it.", "It suits music videos, self-filmed takes and footage that should not cut between images.", "Enable it in Setup before project creation and optionally attach a video clip.", "A long single scene can feel visually static unless the source footage already carries movement.", "The exporter treats it as one timeline segment with one scene duration."),
  c("Projects and setup", "pacing mode", "Pacing mode controls how Scenering estimates scene length from speech or configured duration.", "It helps scene cuts follow narration instead of leaving long silent gaps.", "Choose automatic speech pacing for narration-led work or a fixed approach when timing must be deliberate.", "Do not assume every paragraph is spoken at identical speed; preview narration before final export.", "Pacing changes scene and total video duration and therefore affects export usage minutes."),
  c("Projects and setup", "publish destination", "Publish destination is the target platform profile such as YouTube, Shorts, TikTok or Reels.", "It selects practical defaults for canvas shape, resolution, frame rate and encoding.", "Choose the intended destination in Setup, then review advanced overrides only if necessary.", "A preset improves compatibility but cannot ensure a platform will accept every file after future policy changes.", "Destination settings directly determine final file dimensions and encoding plan."),

  c("Scripts and structure", "a source script", "The source script is the written narration or story Scenering divides into scenes.", "Clear writing gives the scene splitter and visual search better meaning to work with.", "Paste finished prose, review punctuation and separate major ideas before creating scenes.", "Lists of disconnected keywords usually produce weak narration and visual queries.", "The script supplies narration, captions and much of the final timeline duration."),
  c("Scripts and structure", "prepared audio", "Prepared audio is narration recorded or generated outside Scenering and brought into the workflow.", "It lets creators use their own performance or an approved external voice track.", "Use supported upload/import controls and align the project structure with the spoken content.", "Do not upload audio you lack permission to use, and keep a backup of the original file.", "Its decoded duration becomes timing authority where the workflow supports imported narration."),
  c("Scripts and structure", "punctuation", "Punctuation gives speech synthesis pauses and gives scene splitting clues about sentence boundaries.", "It improves natural delivery and prevents ideas from being cut in awkward places.", "Use full stops, commas and paragraph breaks where a speaker would genuinely pause.", "Too many ellipses, symbols or all-caps words can create unnatural speech.", "Punctuation can change narration timing and therefore caption and cut timing."),
  c("Scripts and structure", "scene-worthy ideas", "A scene-worthy idea is a meaningful visual or narrative unit that can be illustrated coherently.", "Grouping by meaning is more watchable than changing images at arbitrary fixed intervals.", "Keep one main action, place or concept per passage when possible.", "Do not force every sentence into a separate scene; closely related sentences often belong together.", "Scene structure determines where transitions, image changes and audio starts occur."),
  c("Scripts and structure", "script revisions", "A script revision changes narration text after a project has already created scenes.", "Revisions fix accuracy, tone, length or clarity without requiring a new project.", "Edit carefully, regenerate affected narration and review the related visual query and captions.", "Changing words without regenerating audio can leave text, voice and captions inconsistent.", "Regenerated speech may alter scene duration and shift later timeline events."),

  c("Scenes", "a scene", "A scene is one timed section containing narration, a visual, framing, motion and a transition to the next section.", "Scenes turn a long script into manageable, editable storytelling units.", "Use Scene Editor to change text, visual, duration, caption inclusion and animation choices.", "Avoid scenes so short that viewers cannot understand the visual or so long that nothing changes.", "Scenes are rendered sequentially on the final timeline."),
  c("Scenes", "scene duration", "Scene duration is how long a scene remains on the timeline.", "It must be long enough for narration and deliberate visual pacing.", "Let decoded narration guide automatic duration or adjust supported timing controls deliberately.", "A duration shorter than the spoken audio can cut narration or cause timing conflicts.", "The sum of scene, intro and outro timing forms total export duration."),
  c("Scenes", "scene order", "Scene order is the sequence in which ideas, visuals and narration play.", "Good order creates a logical story and prevents explanations from arriving before context.", "Reorder scenes with the available scene or timeline controls and preview the joins.", "After reordering, check references such as “next” or “as mentioned earlier.”", "Final export follows the saved scene order exactly."),
  c("Scenes", "duplicate-looking scenes", "Duplicate-looking scenes occur when several scenes use the same or very similar imagery.", "Visual variety helps viewers notice that the story has progressed.", "Use Replace visual or refine each scene query toward its unique subject.", "Do not change images merely for novelty if continuity genuinely requires the same subject.", "Only selected scene media is included in export; search candidates are not."),
  c("Scenes", "scene corrections", "Scene corrections are repeated changes made after previewing text, timing, visual relevance or motion.", "Iteration is expected and does not consume final-export allowance.", "Preview, return to the scene, correct it and preview again until the sequence works.", "Do not confirm a final export simply to inspect a small change when the live preview is sufficient.", "Corrections appear in the next render; previous downloaded files remain unchanged."),

  c("Visual research", "visual research", "Visual research searches available image sources for photographs relevant to a scene.", "It provides selectable source imagery instead of pretending every picture was generated.", "Open scene visual search, review the active query and choose an appropriate result.", "Search relevance is not proof of usage rights; review provider attribution and licence information.", "The chosen visual, not the whole search result set, is used in export."),
  c("Visual research", "a search query", "A search query is the subject phrase sent to configured visual providers.", "Specific nouns, places and actions usually return more useful images than full narration sentences.", "Edit or pin the scene query when the automatic wording misses the intended subject.", "Avoid vague emotional words alone; search services understand concrete subjects more reliably.", "Queries do not appear in the video; they only help select media."),
  c("Visual research", "Pexels and Pixabay", "Pexels and Pixabay are optional configured stock-photo providers supported by Scenering.", "They can broaden high-resolution photographic search when valid API keys are available.", "Add supported keys in API Keys and test them; server-configured keys can also be used.", "Never paste secret keys into public content or share keys you are not permitted to use.", "Provider name and attribution may be included in the credits document, not burned into frames by default."),
  c("Visual research", "Wikimedia Commons", "Wikimedia Commons is a fallback source containing media under varied licences.", "It helps searches continue when optional stock providers return no suitable result.", "Review the source and attribution information associated with a selected Commons image.", "Commons does not mean every file has identical terms; follow the individual file licence.", "The selected image is framed and rendered like other scene visuals."),
  c("Visual research", "the bundled nature library", "The bundled nature library is an offline-friendly fallback deck used when online searches find nothing.", "It prevents a scene search from becoming a dead end.", "Choose a fallback only when it meaningfully supports the scene, or upload/select something more specific.", "A generic landscape may be technically valid but narratively misleading for a precise topic.", "Bundled visuals are rendered locally with the project."),

  c("Framing and images", "cropping", "Cropping removes outer parts of an image so the remaining area fills the video frame without distortion.", "It avoids empty bars while preserving the image’s natural proportions.", "Reposition the crop to keep the subject inside the visible frame and inspect both horizontal and vertical formats.", "Do not crop away faces, text, landmarks or the action the narration refers to.", "The final export contains only the visible crop, not the hidden outer area."),
  c("Framing and images", "aspect ratio", "Aspect ratio is the relationship between frame width and height, such as 16:9 or 9:16.", "It determines whether the video is landscape or vertical and how media must be framed.", "Choose the destination format in Setup and recheck every scene after changing it.", "Changing aspect ratio does not rotate content automatically and can expose poor crops.", "It directly controls exported frame dimensions."),
  c("Framing and images", "cover fit", "Cover fit enlarges media until the entire frame is filled, cropping any overflow.", "It creates a full-bleed look with no empty bands.", "Use crop position and zoom controls to protect the important subject.", "Portrait photos in wide frames can lose large top and bottom areas under cover fit.", "The cover calculation is reproduced in preview and export."),
  c("Framing and images", "contain or blur-fill", "Contain shows the whole source while blur-fill places a blurred copy behind it to fill unused space.", "It protects severe shape mismatches where cropping would remove the subject.", "Choose this framing when the complete image matters more than full-bleed sharp imagery.", "Do not mistake the blurred background for a low-resolution failure; it is an intentional fill treatment.", "Both the sharp source and blurred backing are composited into final frames."),
  c("Framing and images", "image resolution", "Image resolution is the pixel width and height available for display and export.", "Adequate resolution prevents softness when a visual fills a 1080p canvas.", "Prefer verified high-resolution candidates and avoid excessive zoom into small files.", "A large file is not automatically sharp; compression and original focus also matter.", "Low-resolution sources can look blurred because export cannot invent missing detail."),

  c("Voiceover", "voice-over", "Voice-over is spoken narration heard while the selected scene visual is shown.", "It carries information and personality without requiring an on-camera presenter.", "Choose a voice, preview it, generate narration and listen through scene changes.", "Do not select a voice only by name; pace, accent and tone should fit the audience and subject.", "Generated or imported narration is mixed into the final audio track."),
  c("Voiceover", "a voice preset", "A voice preset is a curated narrator choice with an identifier, accent and vocal character.", "Presets make voice selection understandable without browsing hundreds of system voices.", "Preview several presets with representative script text before applying one to all scenes.", "Changing voice can change speaking speed and therefore scene timing.", "The selected voice is synthesized during preview/render when narration is enabled."),
  c("Voiceover", "mood and delivery", "Mood and delivery describe how narration feels—calm, energetic, serious, warm or dramatic.", "Matching delivery to content improves credibility and viewer comfort.", "Use implemented voice options and rewrite punctuation or phrasing when fine control is unavailable.", "Do not over-dramatize sensitive, factual or training content.", "Delivery affects the audio performance but not image resolution."),
  c("Voiceover", "pronunciation dictionary", "A pronunciation dictionary tells supported speech processing how unusual names, abbreviations or terms should sound.", "It prevents repeated mispronunciation across scenes.", "Add a written term and its phonetic guidance, then preview it in context.", "Test changes carefully because phonetic spelling can sound different across voices.", "Corrected pronunciation is heard in regenerated narration and final audio."),
  c("Voiceover", "two-person dialogue", "Two-person dialogue alternates supported voice choices for conversational content where implemented.", "It can distinguish speakers in interviews, lessons or dramatized exchanges.", "Clearly separate speaker lines and use only controls currently available to the selected plan.", "Do not advertise or rely on dialogue behavior that is marked Coming Soon.", "When implemented and enabled, both voices are mixed into the final narration track."),

  c("Captions", "captions", "Captions are timed words displayed over the video to represent narration.", "They improve comprehension, silent viewing and accessibility.", "Enable captions, choose a style and inspect readability against every scene.", "Captions should not cover important subjects, lower thirds or platform interface areas.", "Enabled captions are burned into exported frames; separate subtitle files may also be downloaded where offered."),
  c("Captions", "karaoke highlighting", "Karaoke highlighting changes the appearance of the currently spoken word.", "It helps viewers follow speech timing and adds visual energy.", "Choose a karaoke-capable style and ensure narration has usable word timing.", "Overly fast highlighting or excessive colour can distract from educational content.", "Highlights are rendered frame by frame using spoken offsets."),
  c("Captions", "word-level timing", "Word-level timing records when each spoken word begins or is active.", "It synchronizes highlighting more accurately than dividing a sentence by character count.", "Generate narration with Speechify speech marks and preview the scene.", "A provider response may not contain usable marks for every word; synthesis errors are shown instead of replaced with other speech.", "Available timings guide final caption animation; a local estimate is used only when speech marks are missing."),
  c("Captions", "caption safe area", "Caption safe area is the region where text remains readable and clear of platform controls or frame edges.", "It reduces clipping and avoids competing with logos, CTAs and lower thirds.", "Use the caption position controls and preview in the intended aspect ratio.", "Vertical platforms often place interface buttons along the right and descriptions near the bottom.", "Only the chosen caption position is burned into the exported file; platform overlays are added later by the platform."),
  c("Captions", "caption contrast", "Caption contrast is the visual difference between text and the scene behind it.", "Strong contrast keeps words readable over both bright and dark imagery.", "Use outlines, shadows or background boxes and test across changing visuals.", "White text without a shadow can disappear over clouds, snow or pale walls.", "The exact styling is composited into every exported caption frame."),

  c("Timeline and editing", "the timeline", "The timeline is the time-based view of scenes, audio and inserted studio elements.", "It shows when each item starts, how long it lasts and how layers overlap.", "Scrub the playhead, select blocks and adjust supported bounds or properties.", "Do not confuse visual left-to-right position with scene order after zooming; use the ruler and playhead.", "The renderer evaluates timeline items at their saved timestamps."),
  c("Timeline and editing", "the playhead", "The playhead is the vertical time marker showing the current preview moment.", "It connects the frame on screen with the exact place on the timeline.", "Drag or click the timeline to seek, then insert elements at that time when supported.", "Seeking during active audio can briefly require buffers to catch up; verify by replaying normally.", "The playhead itself is an editor aid and never appears in export."),
  c("Timeline and editing", "a timeline insert", "A timeline insert is an added item such as text, sticker, CTA, music, sound effect or visualiser.", "It lets creative elements appear only where they are needed.", "Choose an item in Video Studio, insert it at the playhead and edit its properties.", "Overlapping too many inserts can hide the scene and compete for attention.", "Active inserts are composited or mixed during their saved time range."),
  c("Timeline and editing", "layer order", "Layer order determines which visual element is drawn in front when items overlap.", "It prevents backgrounds from covering captions, titles or badges.", "Use available stacking or category behavior and inspect overlaps in preview.", "A large opaque overlay can cover every layer beneath it even when timing is correct.", "The same stacking logic is used during export."),
  c("Timeline and editing", "timeline zoom", "Timeline zoom changes how much time fits across the editor width.", "It makes short adjustments easier without changing actual video duration.", "Increase zoom for precise placement and decrease it for an overview.", "Zooming does not trim or stretch media; it changes only the editor scale.", "Timeline zoom is an editor viewing preference and is never included in the exported video."),

  c("Camera movement", "panning", "Panning moves the viewing window horizontally across a still image, as if a camera turns left or right.", "It adds gentle motion and can reveal different parts of a wide image.", "Choose a pan direction or camera-motion option and preview the full scene.", "Do not pan toward empty space or move so quickly that viewers cannot inspect the subject.", "The transform is calculated for every exported frame, producing continuous motion."),
  c("Camera movement", "tilting", "Tilting moves the viewing window vertically across an image, similar to a camera looking up or down.", "It can reveal tall buildings, landscapes or a subject from bottom to top.", "Select an appropriate vertical motion and ensure the crop has enough image beyond the frame.", "A tilt cannot reveal pixels outside the source and may expose poor framing if zoom is too low.", "The vertical motion is rendered into the final video."),
  c("Camera movement", "Ken Burns motion", "Ken Burns motion is a slow combination of zooming and panning across a still photograph.", "It makes static images feel cinematic without inventing movement inside the scene.", "Choose a motion preset and use subtle values that support the narration.", "Excessive zoom can make images soft and repeated identical motion can feel mechanical.", "Preview and export share the same motion transform."),
  c("Camera movement", "zoom in and zoom out", "Zoom in gradually enlarges the subject; zoom out gradually reveals more surroundings.", "Zoom in creates focus or intensity, while zoom out can provide context or closure.", "Choose direction based on the story and keep the subject inside the crop throughout.", "Digital zoom does not add detail and can expose low-resolution imagery.", "The changing scale is encoded frame by frame."),
  c("Camera movement", "motion easing", "Motion easing controls how movement accelerates and slows rather than travelling at one rigid speed.", "Gentle easing makes camera movement and overlays feel more natural.", "Use the provided motion style or animation preset; preview the beginning and end closely.", "Abrupt easing combined with short scenes can look like a jump rather than a deliberate move.", "Easing changes intermediate frames but not the scene’s overall duration."),

  c("Transitions", "a transition", "A transition is the visual change between the end of one scene and the beginning of the next.", "It can smooth a cut, show a shift in topic or add deliberate energy.", "Choose a project transition or supported per-scene option and preview adjacent scenes together.", "Using a dramatic transition at every cut can distract from the story.", "Transitions overlap scene frames for a defined duration during export."),
  c("Transitions", "crossfade", "A crossfade gradually lowers one scene while the next becomes visible.", "It creates a soft, neutral connection between related ideas.", "Use it for calm pacing, memory, passage of time or a less abrupt visual change.", "Crossfading two very different bright images can create a muddy middle frame.", "Both scenes are blended during the transition interval."),
  c("Transitions", "fade to black or white", "A fade passes through a solid black or white frame between scenes.", "It signals a stronger break, chapter change or pause.", "Choose black for a cinematic pause or white for a bright stylistic break when appropriate.", "Frequent full fades can make a short video feel slow and fragmented.", "The solid colour and fade curve are encoded into final frames."),
  c("Transitions", "wipe, push and cover", "Wipes reveal the next scene along an edge; pushes move both scenes; covers place the next scene over the current one.", "Directional movement can reinforce momentum or spatial progression.", "Match direction to reading flow, subject movement or the intended energy.", "Randomly changing direction between every scene makes continuity difficult to follow.", "Scene canvases are translated or clipped during the transition."),
  c("Transitions", "whip pan", "A whip pan is a fast directional transition that imitates a rapid camera swing.", "It creates energy and hides the cut with motion blur-like speed.", "Reserve it for dynamic moments, short-form content or deliberate emphasis.", "It can feel uncomfortable or inappropriate in calm training and reflective stories.", "The fast transform is rendered between scenes; source images themselves remain unchanged."),

  c("Visual styling", "a video filter", "A video filter applies a consistent colour or tonal treatment to the project image.", "It can unify visuals from different sources and establish mood.", "Preview the filter over several bright and dark scenes before applying it globally.", "Strong filters can distort skin, brand colours, maps or informational graphics.", "The filter is processed into exported pixels and cannot be removed from the downloaded file."),
  c("Visual styling", "colour grading", "Colour grading adjusts qualities such as contrast, saturation, warmth and tint for a deliberate look.", "It helps footage feel coherent and can guide emotional tone.", "Use restrained presets or available controls while monitoring detail in highlights and shadows.", "Crushed blacks and clipped highlights permanently hide visual information in export.", "Grading is applied consistently by the preview and render engines."),
  c("Visual styling", "saturation", "Saturation controls the intensity of colours, from muted to vivid.", "Lower saturation can feel serious or archival; higher saturation can feel lively.", "Adjust through a filter or grading preset and check brand colours and natural scenes.", "Too much saturation causes unnatural colour and can make compression artifacts more visible.", "Saturation changes exported pixel colour, not resolution."),
  c("Visual styling", "contrast", "Contrast is the difference between light and dark parts of an image.", "It can improve visual punch and separate subjects from backgrounds.", "Choose a moderate filter and test captions over both the darkest and brightest scenes.", "Excessive contrast removes shadow and highlight detail.", "Final frames retain the selected contrast treatment."),
  c("Visual styling", "opacity", "Opacity describes how transparent an overlay, logo or effect is.", "Lower opacity lets the scene remain visible beneath an element.", "Use the item’s opacity control and inspect it over changing backgrounds.", "Very low opacity can make text unreadable; full opacity can hide important content.", "The chosen alpha value is composited into exported frames."),

  c("Text and graphics", "a text template", "A text template is a designed title or message layout with typography and visual treatment.", "It creates polished on-screen text faster than styling each element manually.", "Pick a template, replace its example content and position it within safe areas.", "Do not leave demonstration wording, names or placeholder copy in the project.", "Template lettering is drawn into final video frames."),
  c("Text and graphics", "a lower third", "A lower third is a text graphic placed in the lower portion of the frame, often naming a person, place or topic.", "It supplies context without interrupting the main visual.", "Keep wording short, place it clear of captions and show it long enough to read.", "On vertical platforms, bottom interface controls may compete with low-positioned graphics.", "The lower third appears only for its configured timeline duration."),
  c("Text and graphics", "a call to action", "A call to action or CTA asks the viewer to do something, such as subscribe, learn more or visit a link.", "It gives the video a clear next step when that request is appropriate.", "Choose a badge style, write honest concise wording and place it near a relevant moment.", "Avoid deceptive urgency, unsupported promises and repeated badges that overwhelm the story.", "The visual CTA is included in export, but it is not automatically a clickable platform link."),
  c("Text and graphics", "a sticker", "A sticker is a decorative or explanatory graphic placed over the video.", "It can add emphasis, personality or a visual cue.", "Select a sticker, scale and position it, then preview its full animation if applicable.", "Too many stickers make professional or informational work feel cluttered.", "The sticker is rendered as an overlay during its timeline range."),
  c("Text and graphics", "a safe margin", "A safe margin is intentional space between important graphics and the frame edge.", "It prevents clipping and reduces conflicts with platform interface overlays.", "Keep logos, captions, titles and CTAs comfortably inside the preview frame.", "Do not assume every television, phone or social app shows every outer pixel unobstructed.", "Safe margins affect placement only; they do not add a visible border unless designed."),

  c("Music and sound", "background music", "Background music is a continuous musical bed mixed underneath narration and scene audio.", "It supports mood, pacing and continuity across visual changes.", "Choose a cleared track, set a restrained volume and listen through spoken sections.", "Music that is too loud masks words; using unlicensed music can trigger platform claims.", "Music is mixed into the final audio stream for its configured duration."),
  c("Music and sound", "voice-priority ducking", "Ducking automatically lowers background music while narration is present.", "It keeps speech intelligible without making music disappear completely.", "Use automatic audio mastering or supported mix controls and preview transitions into silence.", "Extreme ducking can make music pump noticeably between words.", "The gain changes are included in the final mixed audio."),
  c("Music and sound", "a sound effect", "A sound effect is a short audio event such as a whoosh, click, impact or ambience cue.", "It can emphasize a transition, graphic or story moment.", "Place it precisely on the timeline and balance it against narration and music.", "Repeated loud effects can fatigue viewers and may clip the mix.", "Active sound effects are mixed into export at their saved timestamps."),
  c("Music and sound", "audio clipping", "Audio clipping occurs when a signal exceeds the available level and becomes harshly distorted.", "Avoiding clipping keeps narration, music and effects clear.", "Lower individual levels or use the safety limiter in automatic mastering.", "Turning every source to maximum volume makes clipping and listener fatigue likely.", "A limiter can protect the final mix, but it cannot fully repair already distorted source audio."),
  c("Music and sound", "audio mastering", "Audio mastering is the final mix stage using controlled compression, limiting and optional ducking.", "It evens out levels and protects the finished audio from peaks.", "Leave automatic mastering enabled unless you understand and intentionally manage the mix manually.", "Heavy compression can remove natural dynamics and amplify background noise.", "Mastering processes the final audio stream before it is placed in the exported container."),

  c("Audio visualisers", "an audio visualiser", "An audio visualiser is an animated graphic driven by changing audio measurements.", "It gives voice, podcasts and music a visible rhythmic element when the source image is static.", "Add a visualiser in Video Studio, choose a style and preview it while real audio plays.", "A decorative animation that is not connected to audio should not be presented as measured sound.", "The visualiser is drawn into video frames; it does not change the sound itself."),
  c("Audio visualisers", "a waveform", "A waveform represents audio amplitude over time as a line, shape or series of peaks.", "It lets viewers see changes in loudness and speech rhythm.", "Choose a waveform visualiser and set colours and placement for strong contrast.", "A waveform is not a musical transcript and does not show pitch with perfect accuracy.", "The animation follows available analyser data during rendering."),
  c("Audio visualisers", "spectrum bars", "Spectrum bars divide audio energy into frequency ranges from bass to treble.", "They show which frequency bands are active rather than only total loudness.", "Use a spectrum-style visualiser with enough space and a palette matching the project.", "Tiny bars or too many bands become visual noise on phone screens.", "Bar heights are calculated for each frame and included visually in export."),
  c("Audio visualisers", "frequency", "Frequency describes how quickly sound vibrates and is perceived broadly as low bass through high treble.", "Visualisers use frequency ranges to create varied movement across bars or dots.", "Choose a visualiser preset; detailed frequency analysis is handled automatically.", "Frequency graphics are approximations for presentation, not calibrated scientific measurements.", "Frequency analysis drives animation only and does not alter the audio unless a separate effect is applied."),
  c("Audio visualisers", "an analyser node", "An analyser node is a Web Audio component that measures playing audio for visualisation.", "It allows the graphic to respond to the actual narration or music signal.", "Play Speechify-generated or imported audio while a live visualiser is mounted.", "A failed synthesis does not produce replacement speech or a silent audio placeholder.", "When analyser data is available, packed telemetry keeps frame-by-frame visualiser rendering efficient."),

  c("Branding and sections", "the Scenering watermark", "The Scenering watermark is the product logo placed within the video safe area where the plan requires it.", "It identifies the creation tool while remaining separate from a customer’s own logo.", "Preview its placement in horizontal and vertical formats; its layout scales from the output canvas.", "Do not place another opaque graphic directly over it or position it outside the visible crop.", "The same centralized size and inset calculation is used in preview and final export."),
  c("Branding and sections", "a customer logo", "A customer logo is the creator or organization’s own brand mark placed over the video.", "It provides consistent channel or organizational identity.", "Upload a permitted transparent image, set scale, opacity and margin, and inspect it on every background.", "Logos with tiny text, white edges or no transparent padding can become unreadable.", "The logo is composited into final frames at the selected placement."),
  c("Branding and sections", "an intro", "An intro is a short section before the main scene sequence.", "It can establish title, brand or series identity.", "Choose an implemented intro style, replace example text and keep it brief.", "Long repeated intros can reduce viewer retention before the content starts.", "Intro duration is added before scene timing and contributes to total export length."),
  c("Branding and sections", "an outro", "An outro is a closing section after the main scenes.", "It can summarize, credit sources or present a final call to action.", "Choose an outro, edit all placeholder content and match it to the project style.", "Do not let an outro make claims or provide links that are no longer accurate.", "Outro frames and audio extend the exported timeline."),
  c("Branding and sections", "attribution credits", "Attribution credits identify media authors and licences when selected assets require or benefit from credit.", "They help creators meet source obligations and document where media came from.", "Download or copy the generated credits document and review it against each provider source.", "Automated credits are an aid, not legal advice; verify individual licence terms.", "Credits are usually supplied as a separate document unless you intentionally add them on screen."),

  c("Preview and correction", "live preview", "Live preview plays the current project composition inside the editor without creating a final file.", "It supports fast checking of scene cuts, narration, captions, overlays and sound.", "Preview often and revisit the relevant phase when something feels wrong.", "Performance may be less smooth on a busy device, so distinguish editor playback load from export timing accuracy.", "Live previews do not consume final-export allowance."),
  c("Preview and correction", "scrubbing", "Scrubbing means moving the playhead manually through time instead of playing normally.", "It helps locate a cut, caption or overlay quickly.", "Drag or click the timeline and inspect frames around the target moment.", "Scrubbing is not a reliable way to judge audio rhythm because audio may not play continuously.", "Scrubbing changes no project data and never appears in export."),
  c("Preview and correction", "preview buffering", "Preview buffering is the short wait while images, clips or audio are loaded and decoded.", "It prepares media for smooth playback.", "Allow initial loading to finish and replay the section when evaluating synchronization.", "Do not repeatedly click play during loading or assume a temporary pause will exist in the final offline render.", "The preferred exporter renders from decoded timeline data rather than recording preview stalls."),
  c("Preview and correction", "re-rendering a preview", "Re-rendering a preview means checking the project again after corrections without confirming a final export.", "It allows unlimited refinement before usage is recorded.", "Change scenes, voices, captions or effects and replay the affected range.", "Keep track of which change you are testing rather than changing many variables at once.", "Preview repetition consumes no final-export allowance."),
  c("Preview and correction", "preview versus final export", "A preview is an editable inspection experience; a final export is the finished downloadable media file and meaningful usage event.", "Separating them lets creators correct mistakes without paying repeatedly for experimentation.", "Use preview until satisfied, then start the platform-quality render from Render.", "Do not download an old render expecting later editor changes to be included.", "Only confirmed completed final exports are recorded against plan allowance."),

  c("Rendering", "rendering", "Rendering calculates every video frame and audio sample from project settings to create the finished file.", "It turns editable scenes and timeline instructions into media other players can open.", "Open Render, review the summary and keep the page available until completion.", "Closing the browser, exhausting storage or using unsupported codecs can interrupt the job.", "A completed render is saved to the Vault and can be downloaded."),
  c("Rendering", "frame-exact export", "Frame-exact export generates frames from timeline time rather than relying on how fast the screen happens to repaint.", "It preserves smooth movement and synchronization even on a slower computer.", "Use the preferred WebCodecs renderer when the browser supports the selected format.", "Rendering may take longer than the video duration; that does not mean the output will play slowly.", "The resulting file uses constant planned frame timing."),
  c("Rendering", "frames per second", "Frames per second or FPS is the number of video images displayed each second.", "Higher FPS can make motion smoother but increases processing and potentially file size.", "Use destination defaults such as 30 FPS unless the source or platform genuinely needs another value.", "Increasing FPS cannot create authentic motion detail missing from low-frame-rate source footage.", "FPS is encoded into the final video timing profile."),
  c("Rendering", "render progress", "Render progress reports stages, frames, elapsed time, estimated time and output growth.", "It shows that a long job is active and helps diagnose stalls.", "Watch the health panel and keep the device awake and sufficiently charged.", "Estimated completion time can change as complex scenes take different amounts of work.", "Progress indicators are editor information and are not included in the video."),
  c("Rendering", "the Render Vault", "The Render Vault is protected browser storage for completed files waiting to be downloaded.", "It reduces the chance of losing a completed render before saving it to disk.", "Download finished items and free old slots when no longer needed.", "The Vault is not permanent cloud backup and can be affected by browser storage clearing.", "Files leave the Vault after successful download or deletion; the downloaded copy remains yours."),

  c("Export terminology", "a codec", "A codec is the method used to compress and decompress video or audio, such as H.264 and AAC.", "Compatible codecs let platforms and devices play files efficiently.", "Use the destination profile defaults unless a target specifically requires another supported codec.", "A file extension alone does not prove which codec is inside it.", "The codec determines how frame and audio data are encoded in the exported container."),
  c("Export terminology", "a container", "A container is the file structure that holds video, audio and timing tracks, such as MP4 or WebM.", "It packages multiple encoded streams into one playable file.", "Choose a supported destination format; Scenering labels downloads according to the container actually produced.", "Renaming a WebM file to .mp4 does not convert it and can make players reject it.", "Container choice affects compatibility, seeking and metadata organization."),
  c("Export terminology", "bitrate", "Bitrate is the amount of encoded data used per second of video or audio.", "Higher bitrate can preserve more detail but produces larger files.", "Use the quality preset and platform-aware bitrate ladder rather than guessing values.", "Extremely high bitrate wastes storage, while too little creates blockiness and smearing.", "Bitrate strongly influences final file size and compressed quality."),
  c("Export terminology", "constant frame rate", "Constant frame rate means frames are presented at regular intervals throughout the video.", "It improves editing, synchronization and platform compatibility.", "Use the default CFR render profile for normal publishing.", "Do not confuse CFR with constant bitrate; they describe different properties.", "Scenering’s planned timeline emits a consistent frame cadence in supported exports."),
  c("Export terminology", "keyframes", "Keyframes in encoding are complete reference frames from which nearby compressed frames are reconstructed.", "Regular keyframes improve seeking and recovery during playback.", "Let the Master Render Profile choose a practical keyframe interval.", "Encoding keyframes are different from animation keyframes used to define motion states.", "Their interval affects compression efficiency and seeking, not scene order."),

  c("Formats and platforms", "16:9 landscape", "16:9 is a wide aspect ratio commonly used for standard YouTube and desktop video.", "It provides horizontal space for landscapes, demonstrations and side-by-side composition.", "Choose a landscape destination and frame every image for the wider canvas.", "Vertical source images may need blur-fill or careful cropping.", "Typical 1080p landscape export is 1920 by 1080 pixels."),
  c("Formats and platforms", "9:16 vertical", "9:16 is a tall aspect ratio used by Shorts, TikTok and Reels.", "It fills a phone held upright and prioritizes a central subject.", "Choose the vertical destination, reframe scenes and keep text clear of platform side and bottom controls.", "A landscape crop can remove subjects near the left or right edge.", "Typical 1080p vertical export is 1080 by 1920 pixels."),
  c("Formats and platforms", "1080p", "1080p describes a Full HD resolution with 1080 pixels along the shorter landscape height.", "It provides broadly compatible detail without the processing cost of larger formats.", "Use it as the normal high-quality default when source media is sufficiently sharp.", "Exporting a tiny image at 1080p does not restore missing detail.", "Resolution affects frame dimensions, render workload, bitrate and file size."),
  c("Formats and platforms", "platform safe zones", "Platform safe zones are areas less likely to be covered by app buttons, captions, usernames or navigation controls.", "They keep important text and logos visible after upload.", "Preview the intended format and keep critical overlays away from extreme edges and common UI regions.", "Safe-zone guidance can change when platforms redesign their interfaces.", "Scenering preserves your placement; the publishing platform adds its interface afterward."),
  c("Formats and platforms", "format compatibility", "Format compatibility means the destination can decode the chosen container, codecs, dimensions and frame rate.", "Compatible files upload and play more reliably across devices.", "Use a named destination profile and review any compatibility warning before rendering.", "No application can predict every future platform rule, so recheck requirements when an upload is rejected.", "Compatibility settings shape the technical structure of the exported file."),
];

const DIMENSIONS = [
  { key: "meaning", q: (term: string) => `What does “${term}” mean in Scenering?`, a: (x: Concept) => x.meaning },
  { key: "purpose", q: (term: string) => `Why would I use ${term}?`, a: (x: Concept) => x.purpose },
  { key: "control", q: (term: string) => `How do I work with ${term}?`, a: (x: Concept) => x.control },
  { key: "caution", q: (term: string) => `What common mistake should I avoid with ${term}?`, a: (x: Concept) => x.caution },
  { key: "export", q: (term: string) => `How does ${term} affect the final video?`, a: (x: Concept) => x.export },
] as const;

export const FAQ_LIBRARY: FaqEntry[] = CONCEPTS.flatMap((concept, conceptIndex) => {
  const dimensions = conceptIndex < 60 ? DIMENSIONS : DIMENSIONS.filter((dimension) => dimension.key !== "purpose");
  return dimensions.map((dimension) => ({
    id: `faq-${String(conceptIndex + 1).padStart(3, "0")}-${dimension.key}`,
    category: concept.category,
    question: dimension.q(concept.term),
    answer: dimension.a(concept),
    keywords: `${concept.category} ${concept.term} ${concept.meaning}`.toLowerCase(),
  }));
});

export const FAQ_CATEGORIES = ["All", ...Array.from(new Set(CONCEPTS.map((entry) => entry.category)))] as const;

if (FAQ_LIBRARY.length !== 500) {
  throw new Error(`FAQ library must contain exactly 500 entries; found ${FAQ_LIBRARY.length}`);
}
