import { DEVICE_PERFORMANCE } from "./device-guidance";

export interface ManualSection { id: string; title: string; summary: string; paragraphs: string[]; steps?: string[]; note?: string; warning?: string; keywords: string[] }
export interface ManualChapter { id: string; number: number; title: string; description: string; sections: ManualSection[] }
const s = (id: string, title: string, summary: string, paragraphs: string[], keywords: string[], extra: Partial<ManualSection> = {}): ManualSection => ({ id, title, summary, paragraphs, keywords, ...extra });

/** Verified against the current Scenering components and engines. */
export const MANUAL_CHAPTERS: ManualChapter[] = [
  { id: "orientation", number: 1, title: "Orientation", description: "What Scenering does and how the workspace is organized.", sections: [
    s("product-scope", "Product scope", "Scenering builds scene-based videos from scripts, prepared narration or uploaded footage.", ["The implemented project workflow has six phases: Setup, Scenes, Voiceover, Captions, Studio and Render. Each phase edits the same project; moving to another phase does not duplicate the project.", "Scenering is not an automatic publishing service. It creates a downloadable video file. Uploading, scheduling and platform account management happen outside Scenering."], ["workflow","faceless video","scope"]),
    s("interface-map", "Interface map", "The project phase bar is the main navigation inside the studio.", ["Setup opens project creation and output choices. Scenes manages each timed visual section. Voiceover generates or imports narration. Captions controls burned-in subtitle styling. Studio contains the preview, timeline and insert catalog. Render creates and stores the finished file.", "The fixed corner menu is available on public pages, account pages and inside the studio. Signed-in users can open Account, membership and billing from that menu."], ["interface","phase bar","corner menu","navigation"]),
    s("working-method", "Working method and computer performance", "Complete a rough pass through all phases, then refine using previews; faster PCs make complex work smoother and faster to render.", ["A reliable sequence is: confirm source text, create scenes, correct visual relevance, generate narration, style captions, add only necessary Studio inserts, preview the complete timeline, then render.", "Live previews and corrections do not use final-export allowance. A completed final render is the meaningful usage event.", `${DEVICE_PERFORMANCE.testedSystem} ${DEVICE_PERFORMANCE.lowerSpecExpectation}`, `${DEVICE_PERFORMANCE.persistentRender} That persistence helps a modest machine work through a job, but it cannot override a browser or hardware limit; keep the browser open until the render finishes.`, `${DEVICE_PERFORMANCE.recommendation} ${DEVICE_PERFORMANCE.modestMachineTips}`], ["method","preview","final export","computer performance","Celeron","4 GB RAM","render time","persistent render engine"], { steps: ["Create or open a project in Setup.","Review every scene and selected visual.","Generate or import narration.","Check caption readability.","Add and time Studio elements.","Preview from beginning to end.","Render and download the verified file."] })
  ]},
  { id: "account", number: 2, title: "Accounts, Membership and Billing", description: "Registration, sessions, plans, usage and configured checkout.", sections: [
    s("registration", "Registration and verification", "New accounts receive Free membership automatically.", ["Registration requires an email address, display name and password of at least ten characters. Passwords are stored as server-side scrypt hashes, not readable passwords.", "The account must be verified with an expiring email token before login. In development, the configured console email provider logs the message; hosted email delivery requires a provider adapter and credentials."], ["register","verify","password","email"], { steps: ["Choose Get Started Free.","Complete the registration form.","Open the verification link.","Continue to Login and enter the verified credentials."] }),
    s("plans", "Plans and entitlements", "Scenering has Free, SceneFlow and SceneForge plan records.", ["Free supports the complete basic workflow with sample audio visualisers, an animated Subscribe call to action, two background-music tracks, two caption styles, two Shorts and one long-video final download each week. SceneFlow unlocks all creative features and allows 15 final downloads each week. SceneForge also unlocks all creative features and has no Scenering-imposed final-download count, although fetched and upstream API services can still impose their own limits.", "Membership is separate from subscription. An account can move back to Free without automatic project deletion. The owner administrator can grant a verified customer complimentary SceneFlow or SceneForge access for one calendar month or one calendar year; this creates no charge and does not replace a verified paid subscription. For a recipient without an account, the administrator can generate a single-use access code and registration link that grants one full year of the selected plan. The membership year begins when the verified account redeems the code, not when the code is created."], ["free","sceneflow","sceneforge","entitlement","allowance"]),
    s("billing", "Lemon Squeezy billing", "Paid access is controlled by verified subscription events, not by a checkout return page.", ["Checkout URLs, store details, variant IDs, API credentials and the webhook secret are server-side configuration. If checkout URLs are not configured, the Account panel reports that checkout is unavailable.", "The webhook verifies its signature, maps the configured variant, records the event idempotently and updates subscription and membership state."], ["billing","lemon squeezy","webhook","subscription"], { warning: "Never place the Lemon Squeezy API key or webhook secret in frontend code." })
  ]},
  { id: "projects", number: 3, title: "Projects and Storage", description: "Create, reopen, preserve and remove project work.", sections: [
    s("project-record", "What a project contains", "A project joins source text, scenes and browser-stored production settings.", ["Project and scene rows are accessed through the configured Supabase client or its local-storage-backed development substitute. Detailed project settings, timeline inserts and scene metadata are persisted under project-specific browser storage keys.", "Uploaded custom media and finished render blobs use browser storage systems suited to larger files rather than ordinary text-only local storage."], ["project","storage","supabase","local storage"]),
    s("legacy-adoption", "Account ownership and existing projects", "Existing unowned browser projects are preserved during the account transition.", ["When the studio loads, projects without an owner are kept visible and associated with the current account where supported. New project records include the current account identifier.", "Cancelling a subscription does not trigger project deletion. Deliberately deleting a project removes its scenes and associated project-specific local settings."], ["ownership","preservation","delete project"]),
    s("storage-safety", "Storage safety", "Browser storage is not a substitute for keeping original source files.", ["Keep independent copies of uploaded footage, music, narration and important downloaded renders. Clearing site data, browser cleanup tools or private browsing can remove locally retained media.", "The Render Vault protects completed renders in browser storage while they wait for download, but it is not remote backup."], ["backup","browser storage","vault"], { warning: "Download completed work and retain original media outside the browser." })
  ]},
  { id: "setup", number: 4, title: "Project Setup", description: "Source content, destination, canvas, pacing, narration and motion defaults.", sections: [
    s("source", "Title, script and source mode", "Setup creates the project and its initial scene structure.", ["Enter a project title and script for the standard multi-scene workflow. Single-scene mode keeps the whole script in one scene and supports starting from uploaded footage.", "Uploading footage for a single scene switches project voiceover off by default because the clip may already carry its intended sound. Voiceover can be changed later."], ["title","script","single scene","upload footage"]),
    s("destination", "Destination and output profile", "Destination presets choose practical canvas and encoding defaults.", ["Setup can derive aspect ratio, resolution, frame rate and container from a publish destination. Advanced output overrides expose aspect, resolution, FPS, format and audio mastering choices.", "The default render profile targets a web-compatible, constant-frame-rate output. Actual codec/container availability is checked by the browser during rendering."], ["destination","resolution","fps","format","profile"]),
    s("pacing-motion", "Pacing and camera motion", "Pacing determines initial scene length; motion determines the default still-image transform.", ["Automatic speech pacing estimates timing from text and later decoded narration becomes timing authority where available. Global camera motion includes static, zoom, pan and Ken Burns-style options.", "When Scene Animation Effects is enabled, per-scene animation controls replace the global motion choice for active scene movement."], ["pacing","duration","camera motion","ken burns"], { note: "Changing output shape later may require reframing scenes and repositioning overlays." })
  ]},
  { id: "scenes", number: 5, title: "Scenes", description: "Scene structure, text, timing, visuals, transitions and animation.", sections: [
    s("scene-model", "Scene model", "Each scene is an ordered, timed section of the final timeline.", ["A scene stores narration text, a visual query, selected visual, duration, order and additional metadata. Multi-scene scripts are split into balanced passages rather than leaving a deliberately short final fragment.", "Scene duration follows the shared timeline formula used by preview and export, reducing disagreement between scene cuts and narration."], ["scene","order","duration","split"]),
    s("scene-editing", "Editing a scene", "Scene Editor is the place to correct content before adding finishing elements.", ["You can edit scene narration text, replace or reframe the image, use uploaded video where supported, control caption inclusion, choose transition behavior and configure scene animation.", "After changing narration text, regenerate affected voice audio so text, captions and sound remain consistent."], ["scene editor","replace image","clip","caption toggle"]),
    s("transitions", "Transitions", "Transitions control the visual join between scenes.", ["Implemented groups include dissolves, fades, pushes, covers, wipes, reveals and dynamic transitions. Crossfade is a restrained general-purpose option; fade to black or white creates a stronger break; whip-style motion is more forceful.", "Preview adjacent scenes together. A transition is evaluated across its overlap interval and appears in final export."], ["transition","crossfade","wipe","push","whip pan"], { warning: "Using a prominent transition at every cut can obscure the content." })
  ]},
  { id: "visuals", number: 6, title: "Visual Research", description: "Queries, providers, quality checks, selection and attribution.", sections: [
    s("provider-order", "Provider order", "The server searches implemented sources in a fixed fallback order.", ["Pexels is tried first when a custom or server key is available. Pixabay is tried when Pexels returns no results. Wikimedia Commons is the next network fallback. If those sources return nothing, the bundled nature library is returned.", "API Keys lets a user store and verify supported Pexels and Pixabay keys in the browser."], ["pexels","pixabay","wikimedia","fallback","api key"]),
    s("search-broadening", "Queries and broadening", "Scenering widens a query when a specific phrase produces no usable pool.", ["The exact query is tried first. Later search steps remove less useful wording and photography qualifiers until a broader subject remains. The search result records which query actually produced the displayed candidates.", "A manually entered scene query can be pinned so later script edits do not silently replace it."], ["query","broadening","pin query","research"]),
    s("quality-rights", "Quality and source responsibility", "Candidate mapping enforces technical quality but does not replace licence review.", ["The image pipeline keeps photographic sources suitable for a 16:9 1080p workflow. Pexels can serve an exact 1920×1080 crop. Pixabay and Wikimedia candidates must satisfy source and dimension checks.", "Review provider source and attribution requirements. The render screen can produce an attribution document for selected credited media."], ["1920","1080","quality","licence","attribution"], { warning: "Search inclusion is not legal advice or proof that every use is permitted." })
  ]},
  { id: "framing", number: 7, title: "Framing Images and Clips", description: "Crop, contain, blur-fill, aspect ratios and source quality.", sections: [
    s("crop", "Cropping and cover fit", "Cover fit fills the canvas while preserving source proportions.", ["Cropping removes image areas outside the target frame; it does not stretch the source. Reposition the frame so the subject remains visible throughout any camera motion.", "A portrait source used in a 16:9 canvas may lose substantial top and bottom content. A landscape source in 9:16 may lose the sides."], ["crop","cover","reposition","aspect ratio"]),
    s("contain", "Contain and blur-fill", "Contain protects the complete source when aggressive cropping would remove the subject.", ["For severe shape mismatch, blur-fill can show the complete sharp image over a blurred copy filling the unused canvas. This is intentional composition, not failed image loading.", "The same framing engine is called by scene editing, live preview and final export, so the selected fit and crop remain consistent."], ["contain","blur fill","letterbox","framing"]),
    s("clips", "Uploaded video clips", "Custom clips are stored with stable project references and reopened from browser media storage.", ["A clip can supply scene visuals where the workflow supports it. Its decoded media is used during preview and export, and clip decoders are managed in a limited scene window during rendering.", "Keep the original uploaded file. Browser object URLs are temporary and are rebuilt from stored media after reload."], ["video clip","upload","decoder","media storage"])
  ]},
  { id: "voiceover", number: 8, title: "Voiceover", description: "Narrators, generation, imported audio, rotation, pronunciation and echo.", sections: [
    s("voices", "Selecting and generating voices", "The current Speechify narrator catalogue contains twenty profiles: ten male and ten female, preserving Scenering's style archetypes.", ["Add a Speechify API key in API Keys, preview representative text before selecting a narrator, then generate narration with that selected profile. Individual scene audio can also be regenerated.", "Your browser sends the Speechify key and narration request directly to Speechify; Scenering and Cloudflare do not receive the key. Missing keys, provider errors, timeouts or browser-access restrictions are reported; another provider, browser speech or silent placeholder is never substituted."], ["voice","narrator","generate all","tts"]),
    s("rotation-import", "Two-voice rotation and imported narration", "Implemented rotation alternates voice A and voice B by whole scene.", ["Rotation does not switch speakers within one scene; each scene still has one clipped narration buffer. Choose different voices for A and B to make the alternation audible.", "The Import TTS workflow accepts prepared narration audio and labels it as imported rather than claiming Scenering generated it."], ["two voices","rotation","import tts","prepared audio"]),
    s("pronunciation-echo", "Pronunciation and voice echo", "The phonetic dictionary and echo controls alter narration handling.", ["Use the phonetic dictionary for names and specialist terms, then regenerate affected audio. Echo presets include dry/off and several delay/ambience treatments with amount, delay, feedback and tone-related behavior.", "Echo is routed through voice preview, live video preview and final rendering where the audio graph is available."], ["phonetic","pronunciation","echo","reverb","delay"])
  ]},
  { id: "captions", number: 9, title: "Captions", description: "Enablement, timing, style, positioning and readability.", sections: [
    s("caption-control", "Project and scene caption control", "Captions can be enabled project-wide and disabled for individual scenes.", ["The Captions phase edits the shared caption configuration. Scene-level burn-caption settings are obeyed by live preview and export.", "Turning project voiceover off does not automatically make decorative text into captions; captions represent configured scene text and timing."], ["captions","burn in","scene toggle"]),
    s("timing", "Word synchronization", "Generated narration can provide word offsets for karaoke highlighting.", ["Where per-word timing is available, the active word follows actual spoken offsets. Other paths can use timeline-based fallback timing.", "Narration lead-in is included when mapping speech time to scene time, so captions should be checked from the beginning of a scene."], ["word sync","karaoke","timing","lead in"]),
    s("readability", "Style and safe placement", "Caption style combines preset, mode, size, position, case and colours.", ["Preview captions over bright and dark visuals. Background style can remain transparent or use a configured box; text and highlight colours need sufficient contrast.", "Keep captions clear of lower thirds, CTAs, logos and the interface zones commonly overlaid by publishing platforms."], ["caption style","contrast","position","safe area"])
  ]},
  { id: "studio", number: 10, title: "Video Studio and Timeline", description: "Preview, playhead, inserts, stacking and timing.", sections: [
    s("preview-timeline", "Preview and timeline", "The Studio combines the composited video preview with a time-based editor.", ["The playhead represents the current global time. Seeking changes the inspected moment; timeline zoom changes only the editor scale. Scene and insert timing remains unchanged.", "Timeline blocks can be selected, edited, moved or removed through their supported controls. Project-wide music and visualiser inserts are stretched to the full video duration where designed."], ["timeline","playhead","seek","zoom"]),
    s("catalog", "Insert catalog", "Implemented Studio categories include logo, intro, outro, CTA, stickers, text templates, lower thirds, audio visualisers, background music, filters and sound effects.", ["Insert an item at the current playhead, then configure its text, colour, position, scale, timing and category-specific settings. The exact controls vary by item type.", "Filters are project-wide looks rather than short timeline blocks. Intro and outro are sections before and after the main scene sequence."], ["insert","catalog","cta","sticker","lower third","filter"]),
    s("stacking", "Layering and restraint", "Visual inserts are composited with defined stacking behavior over scene content.", ["Check overlapping captions, text cards, badges, stickers, logos and visualisers at their actual times. Audio inserts should be auditioned with narration rather than alone.", "Delete or shorten elements that do not support the content. The timeline can technically hold overlapping items, but readability remains the creator’s responsibility."], ["layer","overlap","stacking","timing"])
  ]},
  { id: "motion", number: 11, title: "Motion, Animation and Transitions", description: "Pan, zoom, scene effects and movement terminology.", sections: [
    s("pan-zoom", "Pan, zoom and Ken Burns", "Pan translates the viewing window; zoom changes scale; Ken Burns combines subtle translation and scale.", ["Pan Left and Pan Right glide horizontally across a still. Slow Zoom In moves toward the subject. Ken Burns Classic uses diagonal pan and zoom.", "Movement cannot reveal pixels outside the source. Cover framing supplies overscan so motion does not expose empty canvas."], ["pan","zoom","ken burns","camera movement"]),
    s("scene-animation", "Per-scene animation effects", "Scene Animation Effects provides scene-specific motion and effect control when enabled.", ["With this system on, Setup’s global Ken Burns selection is preserved but does not drive active per-scene movement. Open Animate Scene from a scene and configure the implemented effect stack there.", "Preview the entire scene, not only its first frame, because motion and atmosphere evolve over time."], ["animate scene","per scene","effects"]),
    s("movement-quality", "Movement quality", "Motion should preserve the subject and match scene duration.", ["Fast motion over a high-detail still can create compression stress. Excessive digital zoom reveals source softness. Repeating the same direction in every scene can feel mechanical.", "The render engine calculates transforms from timeline time, so preferred frame-exact export is not dependent on real-time preview speed."], ["easing","compression","motion quality"])
  ]},
  { id: "audio", number: 12, title: "Music, Effects and Audio Mixing", description: "Music beds, sound effects, mastering, ducking and clipping.", sections: [
    s("music", "Background music", "The Studio catalog provides bundled instrumental tracks and supports user-uploaded music.", ["Only one background-music insert is retained when another is selected through the global music path. Full-video music is stretched to the current project duration.", "Bundled and uploaded media have different licence responsibility. Uploaded music remains the user’s responsibility and is identified accordingly in credits."], ["music","upload","licence","full video"]),
    s("effects", "Sound effects", "Sound effects are short, independently timed audio inserts.", ["Preview a sound, insert it at the playhead and configure timing and volume through supported item properties. Use effects to support a visible event rather than filling every pause.", "Multiple loud sources can sum above a safe level even if each sounds acceptable alone."], ["sound effect","foley","volume","playhead"]),
    s("mastering", "Mastering and ducking", "Automatic mastering uses a gentle compressor, safety limiter and voice-priority ducking.", ["Ducking lowers music while narration is active. The limiter protects the final bus from peaks. Manual mastering mode passes the mix without this automatic stage.", "Listen for music pumping between short phrases. If speech remains unclear, reduce the music insert before relying on stronger processing."], ["mastering","compressor","limiter","ducking","clipping"])
  ]},
  { id: "visualisers", number: 13, title: "Audio Visualisers", description: "Audio-reactive graphics, measurement and rendering.", sections: [
    s("visualiser-basics", "What a visualiser measures", "Audio visualisers draw graphics from analyser data such as waveform samples or frequency energy.", ["The catalog includes radial spectra, waveforms, oscilloscopes, bars, speech-reactive meters and other implemented styles. Each style is a transparent video overlay drawn by Scenering’s renderer.", "A waveform shows changing amplitude. Frequency bars divide energy into bands. An oscilloscope-style view traces the time-domain signal."], ["visualiser","waveform","spectrum","oscilloscope"]),
    s("honest-input", "Available audio input", "A visualiser is only measurement-driven when an audio signal is available to analyse.", ["Speechify-generated or user-imported audio routed through Web Audio can supply analyser data. Synthesis failures are reported rather than replaced with browser speech or fabricated silence.", "Voice echo is included at the listening post where supported, so the visible response can include the audible tail."], ["analyser","web audio","speech synthesis","telemetry"]),
    s("visualiser-design", "Placement and design", "Visualisers are timeline inserts and can cover part or all of the frame depending on style.", ["Choose colours with contrast against the active scene, inspect captions and avoid placing dense bars behind important text. Full-width styles need particular attention in vertical output.", "During offline rendering, packed audio telemetry supplies frame-specific analyser values without retaining thousands of temporary objects."], ["placement","palette","audio telemetry","performance"])
  ]},
  { id: "branding", number: 14, title: "Branding, Text and Sections", description: "Watermarks, logos, templates, lower thirds, intros and outros.", sections: [
    s("logos", "Scenering watermark and customer logo", "The Scenering watermark and uploaded customer logo are separate render elements.", ["Free-plan previews and exports carry the fixed Scenering watermark; paid plans do not. It is controlled by membership, not a project setting, and is composited above creator content. Customer logo settings include enablement, image URL, scale, opacity and margin, and place the logo at the top-right.", "Use transparent artwork with readable shapes. Keep important logo detail away from its own image edges."], ["watermark","customer logo","scale","opacity"]),
    s("text-elements", "Text templates, lower thirds and CTAs", "Text templates create designed cards; lower thirds identify a person or topic; CTAs request an action.", ["Replace all example content. Configure typography, colours, background and motion through the item’s available properties. CTA badges are visual elements and do not create clickable links in the exported video.", "Avoid overlapping caption and lower-third regions, and preview every timed text element at the intended output aspect ratio."], ["text template","lower third","cta","title"]),
    s("intro-outro", "Intro and outro sections", "Intro and outro are project sections outside the main scene sequence.", ["The section builders support configured backgrounds or uploaded clips, titles, logo use and associated sound options. Their durations extend the complete timeline.", "Preview the join from intro to first scene and from last scene to outro. Remove placeholder wording before rendering."], ["intro","outro","section","duration"])
  ]},
  { id: "preview", number: 15, title: "Preview and Quality Control", description: "How to inspect work before committing a final export.", sections: [
    s("preview-types", "Live preview and render preview", "The Studio preview evaluates the project during editing; Render also displays a preview canvas.", ["Both use shared scene framing, filters, captions, motion and watermark logic. Playback can still depend on media loading and device performance.", "A temporary preview stall is not automatically a timing error in frame-exact output. Replay the affected range after loading before diagnosing it."], ["preview","playback","buffering"]),
    s("quality-pass", "Full quality-control pass", "Review picture, sound, text and timing from beginning to end.", ["Check visual relevance, crops, scene order, pronunciation, caption spelling, overlay safe areas, music level, sound effects, intro/outro text and attribution. Test the intended 16:9 or 9:16 canvas rather than assuming layouts transfer.", "Use headphones for audio problems and inspect phone output at a small display size."], ["quality control","checklist","proofread"], { steps: ["Play from the first frame without scrubbing.","Record every issue instead of correcting mid-playback.","Correct one category at a time.","Replay changed joins and audio sections.","Complete one final uninterrupted preview."] }),
    s("usage-boundary", "Preview versus final usage", "Previewing and correcting do not record final-export usage.", ["The account usage API records a completed final render through the final-export path. Free separately enforces its weekly short and long download counts and duration ceilings. SceneFlow uses its configured weekly final-download count; SceneForge has no Scenering-imposed final-download count.", "Final export reserves allowance with the server before encoding and completes that reservation before the finished file is exposed. If authorization or completion cannot be reached, Scenering withholds final delivery; draft previews remain available."], ["usage","allowance","preview","final export"])
  ]},
  { id: "render-profile", number: 16, title: "Render Profile and Encoding", description: "Resolution, FPS, quality, codecs, containers and compatibility.", sections: [
    s("profile", "Master Render Profile", "Render output decisions are resolved from one central profile system.", ["The profile contains destination, canvas, resolution, frame rate, quality, format, bitrate guidance, keyframe interval, naming and compatibility checks. Render displays these choices rather than providing a second independent settings screen.", "Destination profiles inherit central defaults and override only platform requirements."], ["render profile","quality","destination","bitrate"]),
    s("codec-container", "Codec and container", "A codec compresses tracks; a container packages tracks into a file.", ["The preferred target is H.264 video with AAC audio in MP4 when browser WebCodecs support is available. If MP4 encoding is unavailable, the offline path probes VP9/Opus WebM before the explicit real-time MediaRecorder compatibility fallback.", "The downloaded extension follows the container actually produced; renaming an extension is not conversion."], ["codec","container","h264","aac","mp4","webm","vp9","opus"]),
    s("fps-resolution", "Resolution, frame rate and bitrate", "These settings balance compatibility, quality, processing and file size.", ["Resolution defines output dimensions. Constant frame rate defines regular frame cadence. Bitrate controls compressed data per second. Higher values increase processing or size and cannot restore detail absent from source media.", "Use destination defaults unless a delivery requirement justifies an advanced override."], ["resolution","fps","cfr","bitrate","keyframe"])
  ]},
  { id: "render", number: 17, title: "Rendering", description: "Starting, monitoring and recovering a render.", sections: [
    s("preflight", "Render preflight", "Render checks project content, browser support and selected profile before encoding.", ["Open Render after completing the quality pass. Review destination, dimensions, FPS, container, captions, watermark, audio and total duration. Ensure required scene visuals are present.", "Keep sufficient browser storage available and avoid closing the tab during active work."], ["preflight","render summary","storage"]),
    s("offline", "Frame-exact offline export", "The preferred exporter generates frames and audio from timeline time rather than wall-clock playback.", ["It uses WebCodecs and MP4/WebM muxing where supported. Long Chromium renders can stream growing output to protected browser storage with bounded backpressure. Media decoders are kept to a limited scene window.", "Rendering may take longer than video duration without making the resulting playback slow or uneven."], ["offline export","webcodecs","muxer","backpressure","decoder"]),
    s("fallback", "MediaRecorder compatibility fallback", "The fallback records the project in real time when preferred offline configurations are unavailable and fallback is allowed.", ["Visible tabs use animation-frame pacing; hidden-tab support uses worker timing and a watchdog. The Render interface reports compatibility and failure reasons rather than silently mislabelling output.", "Keep the tab and device active. Real-time fallback is more sensitive to browser scheduling than frame-exact export."], ["mediarecorder","fallback","real time","hidden tab"])
  ]},
  { id: "download", number: 18, title: "Vault, Download and Delivery", description: "Secure the finished file and accompanying credits.", sections: [
    s("vault", "The Render Vault", "Completed renders are placed in the browser Vault before download where storage succeeds.", ["The Vault lists finished items with label, duration, size and container. You can preview, download or remove an item. The current maximum is enforced by the Vault implementation; older entries can be displaced when capacity is reached.", "A verified Vault copy protects against losing the immediate result, but it is still browser storage."], ["vault","finished render","browser storage"]),
    s("download", "Downloading the video", "Download writes the rendered blob to a user-selected file or browser download location.", ["Use Download video for the current render or Download from the corresponding Vault row. A successful Vault download clears that Vault slot. If saving is cancelled, the Vault copy remains.", "Confirm the extension matches the displayed container and play the complete downloaded file in an independent player."], ["download","save dialog","mp4","webm"], { steps: ["Wait for Render finished status.","Preview the Vault item if needed.","Choose Download.","Select a file location.","Open the saved file and inspect beginning, middle and end.","Retain the credits document where required."] }),
    s("credits", "Attribution document", "Render can generate a text document listing credited visual, audio and graphics sources used by the project.", ["Copy or download the attribution document and place required credits in the publishing platform’s description or another licence-compliant location.", "Review the generated document. Source terms can differ, and Scenering’s document is production assistance rather than legal advice."], ["credits","attribution","licence","text file"])
  ]},
  { id: "troubleshooting", number: 19, title: "Troubleshooting", description: "Systematic checks for common failures.", sections: [
    s("media", "Missing or blank media", "Start by identifying whether the problem is source loading, framing or storage.", ["For remote images, verify network access and use the image proxy path. For uploaded clips, confirm the original remains available in browser media storage. For blank colour scenes, confirm that blank output was intentional.", "Replace a failed source, confirm that its preview loads at the expected quality, and replay the complete scene before rendering again."], ["blank image","missing media","proxy","clip"]),
    s("audio-sync", "Audio, timing and synchronization", "Regenerate stale narration and verify decoded duration before changing scene timing manually.", ["Check whether voiceover is enabled, whether the scene audio URL matches the selected voice and text, and whether imported audio decoded successfully. Caption timing follows available word offsets and narration lead-in.", "A preview buffer delay should be tested again after media has loaded before treating it as a persistent synchronization problem."], ["audio","sync","duration","caption timing"]),
    s("render-errors", "Render failures", "Use the reported stage and compatibility explanation to identify the failing subsystem.", ["Check browser WebCodecs support, available output storage, source media decoding and whether the selected profile is supported. The render system can build a compatibility fallback report rather than hiding the reason.", "Do not repeatedly start the same failing render without changing the reported condition."], ["render error","webcodecs","storage","compatibility"])
  ]},
  { id: "reference", number: 20, title: "Reference and Terminology", description: "Concise definitions and where each concept applies.", sections: [
    s("video-terms", "Video terms", "Core video and encoding terms used throughout the Scenering studio and render workflow.", ["Aspect ratio: width-to-height relationship. Crop: remove outer source areas to fill a frame. Pan: move the viewing window horizontally. Tilt: move it vertically. Zoom: change displayed scale. FPS: frames shown per second. Transition: the timed visual join between scenes.", "Codec: compression method. Container: package holding video and audio tracks. Bitrate: encoded data per second. CFR: constant frame rate. Keyframe: complete encoded reference frame used for seeking and reconstruction."], ["glossary","aspect ratio","crop","pan","codec","container","bitrate"]),
    s("audio-terms", "Audio terms", "Audio mixing, signal processing and visualisation vocabulary used by Scenering controls.", ["Waveform: amplitude over time. Spectrum: energy divided into frequency bands. Analyser: Web Audio measurement node. Ducking: lower music while speech is active. Compressor: reduce level range. Limiter: prevent peaks exceeding a ceiling. Clipping: distortion caused by exceeding available level.", "Dry voice: narration without echo. Feedback: the amount of delayed signal fed back into an echo path. Damping: reduction of bright high-frequency echo content."], ["waveform","spectrum","ducking","compressor","limiter","clipping"]),
    s("editor-terms", "Editor terms", "Words describing timeline and composition behavior.", ["Playhead: marker for current timeline time. Scrub: seek manually through time. Insert: timed Studio item. Layer order: front-to-back drawing sequence. Opacity: visibility from transparent to solid. Safe area: inset region less likely to be clipped or covered.", "Burned-in caption: subtitle pixels permanently drawn into video frames. Render: create final media from editable instructions. Mux: package encoded tracks into a container."], ["playhead","scrub","insert","opacity","safe area","render","mux"])
  ]}
];

export const MANUAL_SECTIONS = MANUAL_CHAPTERS.flatMap((chapter) => chapter.sections.map((section) => ({ ...section, chapterId: chapter.id, chapterTitle: chapter.title, chapterNumber: chapter.number })));
export const getManualChapter = (id: string) => MANUAL_CHAPTERS.find((chapter) => chapter.id === id) || MANUAL_CHAPTERS[0];
